name: Build and Package Latin Square

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

jobs:
  RunMake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check GCC Version
        run: g++ --version

      - name: Build the project
        run: |
          cd src
          make
          make install
          make clean
          cd ..

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: latin_square_binary
          path: usr/bin/latin_square

  RunTest:
    runs-on: ubuntu-latest
    needs: RunMake
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: latin_square_binary
          path: usr/bin

      - name: Run tests
        run: |
          chmod +x cicd/tests/test.sh
          ./cicd/tests/test.sh

  RunPackage:
    runs-on: ubuntu-latest
    needs: RunTest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: latin_square_binary
          path: usr/bin

      - name: Clean up unnecessary files
        run: |
          rm -rf .git

      - name: Package into .deb
        run: |
          dpkg-deb --build . latin-square_3.0_amd64.deb

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: latin-square
          path: latin-square_3.0_amd64.deb
